/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CountdownWidget: typeof import('./components/widgets/CountdownWidget.vue')['default']
    FooterQuote: typeof import('./components/layout/FooterQuote.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    IconGrid: typeof import('./components/layout/IconGrid.vue')['default']
    IconItem: typeof import('./components/icons/IconItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/layout/SearchBar.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    WidgetWrapper: typeof import('./components/widgets/WidgetWrapper.vue')['default']
  }
}
