/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddDialog: typeof import('./components/dialogs/AddDialog.vue')['default']
    AnniversaryWidget: typeof import('./components/widgets/AnniversaryWidget.vue')['default']
    CalendarWidget: typeof import('./components/widgets/CalendarWidget.vue')['default']
    ContextMenu: typeof import('./components/contextmenu/ContextMenu.vue')['default']
    CountdownWidget: typeof import('./components/widgets/CountdownWidget.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    FolderDialog: typeof import('./components/dialogs/FolderDialog.vue')['default']
    FooterQuote: typeof import('./components/layout/FooterQuote.vue')['default']
    Header: typeof import('./components/layout/Header.vue')['default']
    HotSearchWidget: typeof import('./components/widgets/HotSearchWidget.vue')['default']
    IconEditor: typeof import('./components/icons/IconEditor.vue')['default']
    IconFolder: typeof import('./components/icons/IconFolder.vue')['default']
    IconGrid: typeof import('./components/layout/IconGrid.vue')['default']
    IconItem: typeof import('./components/icons/IconItem.vue')['default']
    MemoWidget: typeof import('./components/widgets/MemoWidget.vue')['default']
    MovieWidget: typeof import('./components/widgets/MovieWidget.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./components/layout/SearchBar.vue')['default']
    SettingsDialog: typeof import('./components/dialogs/SettingsDialog.vue')['default']
    Sidebar: typeof import('./components/layout/Sidebar.vue')['default']
    WeatherWidget: typeof import('./components/widgets/WeatherWidget.vue')['default']
    WidgetConfigDialog: typeof import('./components/dialogs/WidgetConfigDialog.vue')['default']
    WidgetWrapper: typeof import('./components/widgets/WidgetWrapper.vue')['default']
  }
}
